/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_opengles_TriangleRenderActivity */

#ifndef _Included_com_example_opengles_TriangleRenderActivity
#define _Included_com_example_opengles_TriangleRenderActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_opengles_TriangleRenderActivity
 * Method:    createGraphical
 * Signature: (IILandroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_example_opengles_TriangleRenderActivity_createGraphical
  (JNIEnv *, jobject, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
