/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_opengles_ShowPngActivity */

#ifndef _Included_com_example_opengles_ShowPngActivity
#define _Included_com_example_opengles_ShowPngActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_opengles_ShowPngActivity
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_opengles_ShowPngActivity_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_opengles_ShowPngActivity
 * Method:    setSurface
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_example_opengles_ShowPngActivity_setSurface
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_opengles_ShowPngActivity
 * Method:    resetSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_opengles_ShowPngActivity_resetSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_opengles_ShowPngActivity
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_opengles_ShowPngActivity_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
