/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_audio_MainActivity */

#ifndef _Included_com_example_audio_MainActivity
#define _Included_com_example_audio_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_audio_MainActivity
 * Method:    startPlayPcm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_audio_MainActivity_startPlayPcm
  (JNIEnv *, jobject);

/*
 * Class:     com_example_audio_MainActivity
 * Method:    stopPlayPcm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_audio_MainActivity_stopPlayPcm
  (JNIEnv *, jobject);

/*
 * Class:     com_example_audio_MainActivity
 * Method:    startRecorderPcm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_audio_MainActivity_startRecorderPcm
  (JNIEnv *, jobject);

/*
 * Class:     com_example_audio_MainActivity
 * Method:    stopRecorderPcm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_audio_MainActivity_stopRecorderPcm
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
