/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lwl_ffmpegplayer_MainActivity */

#ifndef _Included_com_lwl_ffmpegplayer_MainActivity
#define _Included_com_lwl_ffmpegplayer_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lwl_ffmpegplayer_MainActivity
 * Method:    GetFFmpegVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lwl_ffmpegplayer_MainActivity_GetFFmpegVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
